### ISSUE TITLE
Fares of Czech Airlines, CZ

### ISSUE THREAD

**Issue by gurza** [NemoTravel/nemo.travel.fares#1]
Добавьте, пожалуйста, описание тарифов Чешских авиалиний (CZ): эконом Lite, Plus и Flex, бизнес и бизнес премиум.
Описание на русском языке: http://www.csa.cz/ru/portal/info-and-services/travel-classes.htm
Описание на английском языке: http://www.csa.cz/en/portal/info-and-services/travel-classes.htm

**Comment by ecrofeg** [comment]
У Czech Airlines IATA код OK и по ним информация заведена.

https://github.com/NemoTravel/nemo.travel.fares/blob/master/fareFamilies/OK.json

**Comment by gurza** [comment]
Да, точно. Ошибся, перепутал их с китайцами.
Спасибо!
