### ISSUE TITLE
UT - ошибка в определении семейства Премиум

### ISSUE THREAD

**Issue by gurza** [NemoTravel/nemo.travel.fares#10]
Сейчас регулярное выражение для определения семейства Премиум:
```json
{
  "tariffCodePattern": "^([FZPKLHVOUXRBNGWESTY](FLEX))\\w*$"
}
```

Это неверно.
Правильно (flex -> fl):
```json
{
  "tariffCodePattern": "^([FZPKLHVOUXRBNGWESTY](FL))\\w*$"
}
```

**Comment by ermakae** [comment]
Добрый день, спасибо за сообщение о проблеме.
Внесли исправления https://github.com/NemoTravel/nemo.travel.fares/commit/48cd791eaa0f104ae353aee04db6bb5026d693ef
