### ISSUE TITLE
Отсутствует тариф Аэрофлота "Бизнес Базовый"

### ISSUE THREAD

**Issue by smgladkovskiy** [NemoTravel/nemo.travel.fares#16]
Отсутствует тариф по префиксу кодам тарифа DBS, DBO, IBS, IBO, ZBS, ZBO - БАЗОВЫЙ (BASE)
https://www.aeroflot.ru/ru-ru/online_services/purchase/rate/fare_rules

**Comment by smgladkovskiy** [comment]
@ermakae ✋

**Comment by ermakae** [comment]
@smgladkovskiy Добрый день, добавил недостающую информацию
https://github.com/NemoTravel/nemo.travel.fares/commit/deb98a73b78ac8832b7d89d0d15188978e9af6b7#diff-84ec3d5528cc63aa304cc0434149cacc
