### ISSUE TITLE
Новые тарифы S7

### ISSUE THREAD

**Issue by gurza** [NemoTravel/nemo.travel.fares#17]
Обновите, пожалуйста, информацию о тарифах  S7, они изменились с 3-го ноября.
https://www.s7.ru/ru/fares/

**Comment by gurza** [comment]
Новые семейства тарифов S7
- Базовый (Basic): `^\w(BS)`
- Стандарт (Standard): `^\w(ST)`
- Плюс (Plus): `^\w(PL)`

Для того, чтобы разделить семейства по кабинам нужно классы перечислить. Актуально для Стандарт и Плюс.
- эконом `^(Y|B|H|K|M|L|V|T|R|S|N|Q|O|W)ST`
- бизнеса `^(J|C|D)ST`

Про классы я не уверен. Нужно проверять полноту списка.

Промо описание семейств тарифов от S7: [на русском](https://yadi.sk/i/sWThfMuwPaD_Hg), [на английском](https://yadi.sk/i/EVfy8ht1ztSosw).

**Comment by ermakae** [comment]
Добрый день, спасибо за обращение, внесли изменения
https://github.com/NemoTravel/nemo.travel.fares/commit/ea1fa2c60bb190c4470651130c781c7de6dd544e
