### ISSUE TITLE
Fix IO fare rules

### ISSUE THREAD

**Issue by gurza** [NemoTravel/nemo.travel.fares#19]
Please actualise fare rules for IRAERO (IO).
Source: official air company site, https://iraero.ru/information/rate/

Fixes

1. Names of fare families (brands). Correct names: LIGHT, STANDART, OPTIMAL +. The names do not have a Russian translation.
2. Carry on and baggage for Light, Standard, 
3. For STANDART fares tickets are not refundable and not changeable after departure.

Also It looks that IRAERO hasn't business class fares. Please check it.

**Comment by ermakae** [comment]
Thank you for issue request!
We've made fixes in last commit https://github.com/NemoTravel/nemo.travel.fares/commit/74add8a2403587c5af515ec8016a83c5823e7cf1

**Comment by gurza** [comment]
@ermakae thx
