### ISSUE TITLE
Fix YC fare rules

### ISSUE THREAD

**Issue by gurza** [NemoTravel/nemo.travel.fares#20]
Please actualise fare rules for YAMAL (YC).
Source: official air company site, https://yamal.aero/passengers/services/fares/

Fixes

1. For Budget fare family carry on is 10 kg.
2. For Budget fare family baggage is 2 (not 1) peaces up to 20 kg.
3. Incorrect baggage for all business fares.

**Comment by ermakae** [comment]
Thank you for issue request!
We've made fixes in last commit https://github.com/NemoTravel/nemo.travel.fares/commit/74add8a2403587c5af515ec8016a83c5823e7cf1

**Comment by gurza** [comment]
@ermakae thx
