### ISSUE TITLE
Обновить регулярные выражения для Аэрофлота, SU

### ISSUE THREAD

**Issue by golgovskikh** [NemoTravel/nemo.travel.fares#9]
Houston, we've had a problem

Пример маршрута: Москва-Милан 07.05 туда SU 2410, 15.05 обратно  SU 2413. Класс бронирования R. FareBasis Code = RNBSL. В этом случае подтягиваются описания тарифов как для «Эконом Промо» с багажом, а должны как для «Эконом Лайт» без багажа.

Вот почему это происходит:
https://github.com/NemoTravel/nemo.travel.fares/blob/master/fareFamilies/SU.json
^([R])\\w*\\d*$ - Эконом Промо
^([YBMUKHLQTEN](NB|NO))\\w*$ - Эконом Лайт

Обновите, пожалуйста, регулярные выражения для Аэрофлота, SU.
Вот, что нашли в официальном руководстве: 

Соответствие кодов бронирования, классов обслуживания и типов тарифов
1 буква – код бронирования
Экономический класс: R, N, E, F, Q, L, H, K, U, M, B, Y
Комфорт класс: A, S, W
Бизнес класс: Z, I, D, C, J
2-3 буквы – код бренда и тип маршрута
SX – Промо (RT)
SO – Промо (OW)
VU – Бюджет (RT)
VO – Бюджет (OW)
CL – Оптимум (RT) (для отдельных направлений FL33)
CO – Оптимум (OW) (для отдельных направлений FX32)
FM – Премиум (RT)
FO – Премиум (OW)
4 буква – код сезона (может отсутствовать)
L - низкий
K - межсезонный
H - высокий
Могут быть добавлены коды дней недели, служебные символы и т.п.
Также существуют отдельные обозначения для различных специальных тарифов
(единые, субсидированные, туроператорские и т.п.)

**Comment by ermakae** [comment]
@golgovskikh 
Добрый день, большое спасибо за баг-репорт!
Мы внесли исправления:
https://github.com/NemoTravel/nemo.travel.fares/commit/83c27dd47b8b96927f9c45e57047cd2a6d9ce83a
